local M = {}

local lines = {
  "  CHEATSHEET — atajos y motions",
  "  ───────────────────────────────────────────────────────────",
  "  Cierra con: q   |   <Esc>",
  "",
  "  ── LEADER ─────────────────────────────────────────────────",
  "  Tu <leader> es la barra espaciadora (default).",
  "",
  "  ── ARCHIVO / VENTANA ──────────────────────────────────────",
  "  <leader>w        Guardar",
  "  <leader>q        Salir",
  "  <leader>e        Abrir Oil (file explorer)",
  "  -                Abrir Oil en directorio padre",
  "  <C-h/j/k/l>      Moverse entre splits (izq/abajo/arriba/der)",
  "  :split / :vsplit Crear split horizontal / vertical",
  "",
  "  ── TELESCOPE (búsqueda) ───────────────────────────────────",
  "  <leader>ff       Find Files",
  "  <leader>fg       Live Grep (buscar texto en proyecto)",
  "  <leader>fb       Buffers abiertos",
  "  <leader>fh       Help tags",
  "  <leader>/        Fuzzy find dentro del archivo actual",
  "",
  "  ── DIAGNÓSTICOS / LSP ─────────────────────────────────────",
  "  <leader>d        Ver diagnóstico de la línea (float)",
  "  <Esc>            Limpiar highlight de búsqueda",
  "  gd               Go to definition (LSP)",
  "  gr               Referencias (LSP)",
  "  K                Hover docs (LSP)",
  "  [d / ]d          Diagnóstico anterior / siguiente",
  "",
  "  ── DEBUGGER (DAP) ─────────────────────────────────────────",
  "  <F5>  / <leader>Dc   Continue / Start",
  "  <F10> / <leader>Do   Step Over",
  "  <F11> / <leader>Di   Step Into",
  "  <F12> / <leader>DO   Step Out",
  "  <leader>Db           Toggle breakpoint",
  "  <leader>DB           Breakpoint condicional",
  "  <leader>Du           Toggle UI",
  "  <leader>De           Eval expresión (normal/visual)",
  "  <leader>Dr           Abrir REPL",
  "  <leader>Dl           Run last config",
  "  <leader>Dt           Terminate",
  "  <leader>DC           Limpiar todos los breakpoints",
  "",
  "  ── RUST (rustaceanvim, en buffers .rs) ────────────────────",
  "  <leader>Ra      Code actions",
  "  <leader>Rr      Runnables (cargo run / test)",
  "  <leader>Rd      Debuggables (lanza con DAP + codelldb)",
  "  <leader>Re      Expandir macro",
  "  <leader>Rh      Hover actions",
  "  <leader>Rp      Ir al módulo padre",
  "  <leader>Rc      Abrir Cargo.toml",
  "  <leader>RR      Reload workspace (re-index rust-analyzer)",
  "  K               Hover (docs)",
  "  :RustLsp <cmd>  Ver todos los comandos disponibles",
  "",
  "  ── FLUTTER (flutter-tools.nvim) ───────────────────────────",
  "  <leader>Fr      Flutter Run",
  "  <leader>FR      Hot Restart",
  "  <leader>Fl      Hot Reload",
  "  <leader>Fq      Quit (parar la app)",
  "  <leader>Fd      Lista de devices",
  "  <leader>Fe      Lista de emuladores",
  "  <leader>FD      Abrir DevTools",
  "  <leader>Fo      Toggle outline de widgets",
  "  <leader>Fp      flutter pub get",
  "  <leader>Fu      flutter pub upgrade",
  "  <leader>Fc      Limpiar log",
  "  <leader>Fs      Go to Super (clase padre)",
  "",
  "  ── MOTIONS BÁSICOS (modo normal) ──────────────────────────",
  "  h / j / k / l    Izquierda / abajo / arriba / derecha",
  "  w / W            Siguiente palabra (W ignora puntuación)",
  "  b / B            Palabra anterior",
  "  e / E            Final de palabra",
  "  0                Inicio de línea",
  "  ^                Primer caracter no-blanco de la línea",
  "  $                Final de línea",
  "  gg               Inicio del archivo",
  "  G                Final del archivo",
  "  {número}G        Ir a la línea {número} (ej. 42G)",
  "  :{número}        Ir a la línea {número}",
  "  <C-u> / <C-d>    Scroll media página arriba / abajo",
  "  <C-b> / <C-f>    Scroll página completa arriba / abajo",
  "  zz / zt / zb     Centrar / arriba / abajo la línea actual",
  "  H / M / L        Tope / medio / fondo de la pantalla visible",
  "  %                Saltar al paréntesis/llave/bracket pareja",
  "  *  /  #          Buscar palabra bajo el cursor (adelante/atrás)",
  "  n / N            Repetir búsqueda (siguiente / anterior)",
  "  f{x} / F{x}      Saltar al próximo char {x} (adelante/atrás)",
  "  t{x} / T{x}      Igual que f pero se detiene ANTES del char",
  "  ; / ,            Repetir último f/t (adelante / atrás)",
  "",
  "  ── EDICIÓN ────────────────────────────────────────────────",
  "  i / a            Insert antes / después del cursor",
  "  I / A            Insert al inicio / final de línea",
  "  o / O            Nueva línea abajo / arriba (modo insert)",
  "  x                Borrar caracter bajo el cursor",
  "  r{x}             Reemplazar caracter por {x}",
  "  u                Undo",
  "  <C-r>            Redo",
  "  .                Repetir última edición",
  "  dd / yy / cc     Borrar / copiar / cambiar línea entera",
  "  d{motion}        Borrar con motion (ej. dw, d$, dgg)",
  "  y{motion}        Copiar con motion (ej. yw, y$)",
  "  c{motion}        Cambiar con motion (ej. cw, ci\")",
  "  p / P            Pegar después / antes del cursor",
  "  >> / <<          Indentar / des-indentar línea",
  "  J                Unir línea siguiente con la actual",
  "",
  "  ── TEXT OBJECTS (combinan con d/y/c/v) ────────────────────",
  "  iw / aw          Inner word / a word (con espacios)",
  "  i\" / a\"          Dentro / incluyendo comillas dobles",
  "  i' / a'          Dentro / incluyendo comillas simples",
  "  i( / a( (o ib)   Dentro / incluyendo paréntesis",
  "  i{ / a{ (o iB)   Dentro / incluyendo llaves",
  "  it / at          Dentro / incluyendo tags HTML/XML",
  "  ip / ap          Párrafo",
  "  Ejemplos: ci\"  cambia contenido entre comillas",
  "            da(   borra paréntesis y contenido",
  "            yi{   copia contenido de las llaves",
  "",
  "  ── MODO VISUAL ────────────────────────────────────────────",
  "  v                Visual char",
  "  V                Visual línea",
  "  <C-v>            Visual block (columnas)",
  "  gv               Re-seleccionar última selección",
  "  o                Mover cursor al otro extremo de la selección",
  "",
  "  ── BUFFERS / TABS ─────────────────────────────────────────",
  "  :bn / :bp        Siguiente / anterior buffer",
  "  :bd              Cerrar buffer",
  "  <leader>fb       Lista de buffers (Telescope)",
  "  :tabnew          Nueva tab",
  "  gt / gT          Siguiente / anterior tab",
  "",
  "  ── BÚSQUEDA / REEMPLAZO ───────────────────────────────────",
  "  /{texto}         Buscar adelante",
  "  ?{texto}         Buscar atrás",
  "  :%s/old/new/g    Reemplazar en todo el archivo",
  "  :%s/old/new/gc   Reemplazar con confirmación",
  "  :s/old/new/g     Reemplazar en la línea actual",
  "",
  "  ── MARCAS / SALTOS ────────────────────────────────────────",
  "  m{a-z}           Marcar posición con letra",
  "  '{a-z}           Saltar a la marca",
  "  <C-o> / <C-i>    Salto anterior / siguiente (jumplist)",
  "  ``               Volver a la posición previa",
  "",
  "  ── TREESITTER / VARIOS ────────────────────────────────────",
  "  za               Toggle fold",
  "  zR / zM          Abrir / cerrar todos los folds",
  "  :Mason           Gestor de LSP/DAP/formatters",
  "  :Lazy            Gestor de plugins",
  "  :checkhealth     Diagnóstico de nvim",
  "",
  "  ───────────────────────────────────────────────────────────",
  "  Tip: :verbose map <tecla>  muestra dónde se definió un keymap",
}

function M.open()
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
  vim.bo[buf].modifiable = false
  vim.bo[buf].buftype = "nofile"
  vim.bo[buf].bufhidden = "wipe"
  vim.bo[buf].filetype = "markdown"

  local width = math.min(80, math.floor(vim.o.columns * 0.9))
  local height = math.min(#lines + 2, math.floor(vim.o.lines * 0.9))
  local row = math.floor((vim.o.lines - height) / 2)
  local col = math.floor((vim.o.columns - width) / 2)

  local win = vim.api.nvim_open_win(buf, true, {
    relative = "editor",
    width = width,
    height = height,
    row = row,
    col = col,
    style = "minimal",
    border = "rounded",
    title = " Cheatsheet ",
    title_pos = "center",
  })

  vim.wo[win].wrap = false
  vim.wo[win].cursorline = true

  local function close() pcall(vim.api.nvim_win_close, win, true) end
  vim.keymap.set("n", "q",     close, { buffer = buf, nowait = true, silent = true })
  vim.keymap.set("n", "<Esc>", close, { buffer = buf, nowait = true, silent = true })
end

vim.api.nvim_create_user_command("Cheatsheet", M.open, { desc = "Mostrar guía rápida de atajos" })
vim.api.nvim_create_user_command("Atajos",     M.open, { desc = "Mostrar guía rápida de atajos" })

return M
